# Generated by Django 5.2.3 on 2025-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hygienereport',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='hygienereport',
            name='issue_type',
            field=models.CharField(max_length=100),
        ),
    ]
