# Generated by Django 5.2.3 on 2025-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0002_rename_timestamp_hygienereport_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hygienereport',
            name='photo',
        ),
        migrations.AddField(
            model_name='hygienereport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='hygienereport',
            name='issue_type',
            field=models.CharField(max_length=50),
        ),
    ]
