# Generated by Django 5.1.6 on 2025-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hygienereport',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hygienereport',
            name='resolver_points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
