# Generated by Django 5.1.6 on 2025-06-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0007_hygienereport_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hygienereport',
            name='resolution_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
