# Generated by Django 5.1.6 on 2025-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0008_hygienereport_resolution_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='hygienereport',
            name='resolution_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
