services:
  - type: web
    name: swasthgram-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
    runtime: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
