services:
  - type: web
    name: swasthgram-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_project_name.wsgi"
    runtime: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
