services:
  - type: web
    name: swasthgram-backend
    env: python
    buildCommand: "python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn your_project.wsgi:application"
    runtime: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
