services:
  - type: web
    name: swasthgram-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi --config gunicorn_config.py"
    runtime: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
